import { GitFork as Github, Mail, MapPin, Phone, Send } from "lucide-react";
import { useState } from "react";
import Reveal from "../components/Reveal";
import cv from "../data/cvData";

export default function ContactPage() {
  const [form, setForm] = useState({ name: "", email: "", message: "" });
  const submit = (event) => { event.preventDefault(); const subject = encodeURIComponent(`Portfolio enquiry from ${form.name || form.email}`); const body = encodeURIComponent(`${form.message}\n\nFrom: ${form.name} <${form.email}>`); window.location.href = `mailto:${cv.email}?subject=${subject}&body=${body}`; };
  return <main className="container py-16 sm:py-20"><div className="grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><Reveal><p className="eyebrow">Contact</p><h1 className="mt-3 font-['Space_Grotesk'] text-4xl font-bold tracking-tight text-white sm:text-5xl">Let’s build something dependable.</h1><p className="mt-6 max-w-xl leading-8 text-slate-300">I’m interested in Java backend opportunities where I can contribute to a thoughtful team, learn quickly, and build reliable systems.</p><div className="mt-10 space-y-5 text-sm text-slate-300"><a className="flex items-center gap-3 hover:text-cyan-200" href={`mailto:${cv.email}`}><Mail className="text-cyan-300" size={18} />{cv.email}</a><a className="flex items-center gap-3 hover:text-cyan-200" href={`tel:${cv.phone.replaceAll(" ", "")}`}><Phone className="text-cyan-300" size={18} />{cv.phone}</a><a className="flex items-center gap-3 hover:text-cyan-200" href={cv.github} target="_blank" rel="noreferrer"><Github className="text-cyan-300" size={18} />github.com/CThu01</a><p className="flex items-center gap-3"><MapPin className="text-cyan-300" size={18} />{cv.location}</p></div></Reveal><Reveal delay={0.1}><form onSubmit={submit} className="surface p-6 sm:p-8"><p className="text-lg font-bold text-white">Send a message</p><p className="mt-2 text-sm leading-6 text-slate-400">This opens your email application with your message prefilled.</p><div className="mt-7 grid gap-4"><label className="grid gap-2 text-sm font-semibold text-slate-200">Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded-xl border border-white/10 bg-slate-950/50 px-4 py-3 text-white outline-none transition focus:border-cyan-300/60 focus:ring-2 focus:ring-cyan-300/20" /></label><label className="grid gap-2 text-sm font-semibold text-slate-200">Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="rounded-xl border border-white/10 bg-slate-950/50 px-4 py-3 text-white outline-none transition focus:border-cyan-300/60 focus:ring-2 focus:ring-cyan-300/20" /></label><label className="grid gap-2 text-sm font-semibold text-slate-200">Message<textarea required rows="6" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} className="resize-y rounded-xl border border-white/10 bg-slate-950/50 px-4 py-3 text-white outline-none transition focus:border-cyan-300/60 focus:ring-2 focus:ring-cyan-300/20" /></label><button className="button-primary mt-2 w-fit" type="submit">Send message <Send size={17} /></button></div></form></Reveal></div></main>;
}
